name: karman
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - pip
  - matplotlib
  - jupyter
  - pytorch
  - scikit-learn
  - pandas
  - pytables
  - tqdm
  - pyfiglet
  - termcolor
  - wandb
  - netcdf4
  - cftime
  - huggingface_hub
  - h5py
  - pip:
    - nrlmsise00
    - spaceweather
    - pyatmos
    - tft-torch 
