name: build

env:
  # Use the same ssh-agent socket value across all jobs
  # Useful when a GH action is using SSH behind-the-scenes
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Start ssh-agent but set it to use the same ssh_auth_sock value.
      # The agent will be running in all steps after this, so it
      # should be one of the first.
      - name: Set up Python 3.8
        uses: actions/setup-python@v4 
        with:
          python-version: 3.8
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfftw3-dev libopenblas-dev
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib
          pip install jupyter
          pip install numpy
          pip install torch==1.11.0+cpu torchvision==0.12.0+cpu torchaudio==0.11.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
          pip install .[dev]
          pip install sphinx
          pip install sphinx-book-theme
          pip install myst-nb
          cd doc
          make html linkcheck      
      
      - name: Upload to github pages 🚀
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/_build/html # The folder the action should deploy.